### ISSUE TITLE
HBox, VBox are deprecated.

### ISSUE THREAD

**Issue by jonathanstowe** [finanalyst/GTK-Simple#27]
The HBox and VBox widgets have been deprecated since Gtk+ 3.2 in favour of using a plain Box with the appropriate orientation property.  (It is also hinted that Box itself may be deprecated in the future.)

In order to maintain backward compatibility, the HBox and VBox should probably re-implemented in terms of the box constructor.

I'll implement if no-one else does it first.

**Comment by azawawi** [comment]
Any update on this one?

**Comment by MARTIMM** [comment]
Read this at [the site of Maya](https://bugs.launchpad.net/maya/+bug/965469). A note made on 2012-03-26 by Corentin Noël. The discussion there made clear that any of VBox, HBox, and Box would better be done with Grid.

A note in this discussion;
**If you want your code to be future-proof, the recommendation is to switch to GtkGrid, since GtkBox is going to be deprecated in favor of the more flexible grid widget eventually. For more information about migrating to GtkGrid, see Migrating from other containers to GtkGrid.**

**Comment by finanalyst** [comment]
GTK 4 has been launched. GTK 3 will be supported, but API changes like this one are unlikely. So no need for any work on this issue. Closing
