### ISSUE TITLE
Provide widget constructor candidate that takes GtkWidget

### ISSUE THREAD

**Issue by jonathanstowe** [finanalyst/GTK-Simple#31]
It would be useful to implementing parts of the API and necessary to move GtkBuilder forward if a constructor candidate was available which took the raw GtkWidget object.

It would be nice if this could happen without adding it to each widget class.

**Comment by slobo** [comment]
Perhaps a good time to split the giant `Simple.pm6` into multiple files? Of course, it would be great to still just be able to do `use GTK::Simple` without needing to import every component separately. I just find I get lost when source is > few hundred loc, fold markers notwithstanding :)

**Comment by finanalyst** [comment]
It seems to me that there are two situations here:
a) a need for something quick and simple, with no need for knowledge 
about GTK. Most of the work is done in GTK::Simple and only a few 
widgets are available. I think by and large, GTK::Simple meets this 
need. It has done for me.

b) a need for something that can be interfaced with other tools like 
Glade, allowing far greater flexibility. I would suggest this be a 
different module, say GTK::General. This would be a different sort of 
module because GTK is far more complex.

Although ultimately it may turn out that a single module will meet both 
needs in time, it may be better to separate the development paths. It 
would free the developers of the generic module from maintaining 
backwards compatibility with GTK::Simple

**Comment by jonathanstowe** [comment]
Hi,
This stuff is worthwhile discussing but can I suggest starting a new issue for it? 

The original ticket is to cover off some work that I believe needs to be done to make implementing a number of things a lot easier, it will get closed when that work is done :)

**Comment by slobo** [comment]
I don't mind doing the grunt work of adding a `multi submethod BUILD(:$!gtk_widget){}` to each class, as long as you think it's the best choice right now.

**Comment by finanalyst** [comment]
GTK::Simple has been refactored since this issue was raised, so I am marking it as resolved.
Since the GTK::Simple::Widget role provides $!gtk_widget and all GTK:S class do GTK::Simple::Widget, I think this resolves this issue. If not, more clarity about what is needed and reopen the issue
