### ISSUE TITLE
Allow setting font within a TextView

### ISSUE THREAD

**Issue by retupmoca** [finanalyst/GTK-Simple#7]

**Comment by jonathanstowe** [comment]
Hi,
I think that it's something that would have to be implemented for _all_ widgets by implementing the pango font stuff:

https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-font-options

because that will require a whole bunch of other stuff regarding  Pango to be implemented I don't think it's something that will get done immediately.

The only interface regarding the font on the text view is toggling between proportional and monospace:

https://developer.gnome.org/gtk3/stable/GtkTextView.html#gtk-text-view-set-monospace

That is quite doable and I'll have a look today.

Hope that helps.

**Comment by jonathanstowe** [comment]
I am however going to do #28 before adding any more properties to the interface.

**Comment by finanalyst** [comment]
I implemented pango for Label, see MarkUpLabel.

Very simple changes to Label. But I don't know how general these change can be

**Comment by finanalyst** [comment]
Ignore last remark. My bad. Marked label is just a call to gtk_marked_label. It uses pango internally, but can't be generalised.

**Comment by finanalyst** [comment]
With GTK 4 launched, this enhancement for GTK 3 require a huge amount of effort. Not cost effective, so closing. MarkUpLabel allows for coloured text and should meet most font type issues.

**Comment by Xliff** [comment]
Please note that there is [p6-Pango](https://github.com/Xliff/p6-Pango). It's still experimental, but I have found it workable enough. Would be nice to get more eyes on it so I can find and eliminate any bugs that are there.
